spring:
  profiles:
    active: local
  application:
    name: gitlab-merge-request
  datasource:
    url: jdbc:postgresql://172.25.16.68:5432/db_gitlab
    driver-class-name: org.postgresql.Driver
    username: sa
    password: 6789@jkl
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
# gitlab服务地址
gitlab:
  server: http://gitlab.thunisoft.com

# 配置不走登录验证的页面
non-require-login: /assets/**,/favicon.ico,/error/**,/login
shiro:
  loginUrl: /login
