spring:
  profiles:
    active: local
  application:
    name: gitlab-merge-request
  datasource:
    url: jdbc:postgresql://ip:port/db_gitlab
    driver-class-name: org.postgresql.Driver
    username: root
    password: 123456
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
# gitlab服务地址
gitlab:
  server: http://gitlab.com

# 配置不走登录验证的页面
non-require-login: /assets/**,/favicon.ico,/error/**,/login
shiro:
  loginUrl: /login
